[Color]

; ダイアログなど、ほぼすべてのコントロールで、背景に使用されます。
Background=202020

; メニューの縁やトラックバーのつまみの縁に使用されます。
WindowBorder=585858

; ワークスペースの無効状態のセパレータに使用されます。
WindowSeparator=000000

; メッセージボックス下部の背景に使用されます。
Footer=304080

; 使用されません。
FooterProgress=903838,b84848

; 非アクティブなウィンドウの背景に使用されます。
; ワークスペースの通常状態のキャプションの背景に使用されます。
Grouping=383838

; アクティブなウィンドウの背景に使用されます。
GroupingHover=404040

; ワークスペースの選択状態のキャプションの背景に使用されます。
GroupingSelect=484848

; ウィンドウやワークスペースのキャプションの縁に使用されます。
GroupingSeparator=4c4c4c

; スクロールバーの背景・ヘッダーコントロール・メニューのセパレータなどに使用されます。
TitleHeader=404040

; ほぼすべてのコントロールで、プッシュ状態の縁に使用されます。
BorderSelect=e0e0e0

; ほぼすべてのコントロールで、通常状態の縁に使用されます。
Border=909090

; ほぼすべてのコントロールで、ホット状態の縁に使用されます。
BorderFocus=8080e0

; ほぼすべてのコントロールで、通常状態の文字列に使用されます。
Text=ffffff

; ほぼすべてのコントロールで、無効状態の文字列に使用されます。
TextDisable=909090

; エディットボックスやリストボックスなどの選択状態の背景に使用されます。
TextSelect=6060e0

; ほぼすべてのコントロールで、通常状態の背景に使用されます。
ButtonBody=606060

; ほぼすべてのコントロールで、ホット状態の背景に使用されます。
ButtonBodyHover=808080

; ほぼすべてのコントロールで、プッシュ状態の背景に使用されます。
ButtonBodyPress=a0a0a0

; ほぼすべてのコントロールで、無効状態の背景に使用されます。
ButtonBodyDisable=484848

; ほぼすべてのコントロールで、選択状態の背景に使用されます。
ButtonBodySelect=7070c0

; スライダーで、選択部分の縁に使用されます。
TrackBarRange=282828

; スライダーで、選択部分の背景に使用されます。
SliderCursor=b88070

; スライダーで、つまみの背景に使用されます。
SliderThumbBody=707070

; スライダーで、ホットまたはプッシュ状態のつまみの背景に使用されます。
SliderThumbBodyFocus=b88070

; スライダーで、つまみの縁に使用されます。
SliderThumbBorder=d8d8d8

; 使用されません。
ZoomGauge=60a0ff
ZoomGaugeHover=80c0ff
ZoomGaugeOff=204080
ZoomGaugeOffHover=3060a0

; フレーム選択範囲内の背景に使用されます。
FrameRangeSelect=6060e0

; フレーム選択範囲外の背景に使用されます。
FrameRangeOutside=383850

; フレームカーソルの色に使用されます。
; アルファは使用されません。
; ただし、カーソルはxorで描画されます。
FrameCursor=c83030e0

; 使用されません。
FrameCursorWide=c8303080
PlayerCursor=e0e080e0
GuideLine=606060c0

; レイヤーの背景に使用されます。
Layer=404040

; タイムライン(のヘッダー部分など)の背景に使用されます。
LayerHeader=4a4a4a

; 縞模様レイヤーの場合、奇数レイヤーの背景に使用されます。
LayerHover=585858

; 非表示状態のレイヤーの背景に使用されます。
LayerDisable=343434

; 選択レイヤーを描画する場合、選択レイヤーの背景に使用されます。
LayerSelect=3c4054

; グループ制御などの対象範囲の背景に使用されます。
; アルファは使用されません。
LayerRange=70707038

; 使用されません。
LayerRangeFrame=707070c8
